export class Register {
    id:number;
    ssn:string;
    account_id:number;
    phone_number:string;
    university_id:number;
    department_id:number;
    class_no:number;
    student_number:string;
    mother_name:string;
    father_name:string;
    birth_place:string;
    birthdate:Date;
    city:string;
    district:string;
    cover_no:number;
    family_serial_no:number;
    serial_no:number;
    neighborhood:string;
    blood_type:string;
    address:string;
}